### ISSUE TITLE
Mal Fails to Compile on Windows 64 bit, Go 1.4.2

### ISSUE THREAD

**Issue by Immortalin** [kanaka/mal#68]
`# readline
src\readline\readline.go:12:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
make: *** [step0_repl] Error 2`

**Comment by kanaka** [comment]
You'll probably either need [readline for windows](http://gnuwin32.sourceforge.net/packages/readline.htm) or make readline linking optional.
